sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt ++2.11.8 test
  # avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
